package ru.theframetrip.kitchenlegacy.ability.predel;

import net.minecraft.core.*;import net.minecraft.resources.*;import net.minecraft.server.level.*;import net.minecraft.tags.BlockTags;import net.minecraft.world.entity.*;import net.minecraft.world.item.ItemStack;import net.minecraft.world.level.*;import net.minecraft.world.level.block.*;import net.minecraft.world.level.block.state.BlockState;import net.minecraft.world.phys.*;import net.minecraftforge.common.MinecraftForge;import net.minecraftforge.event.TickEvent;import net.minecraftforge.event.level.ChunkEvent;import net.minecraftforge.eventbus.api.SubscribeEvent;import net.minecraftforge.fml.common.Mod;import ru.theframetrip.kitchenlegacy.KitchenLegacyMod;import ru.theframetrip.kitchenlegacy.event.PredelRiftPermissionEvent;import ru.theframetrip.kitchenlegacy.registry.*;
import java.util.*;

@Mod.EventBusSubscriber(modid=KitchenLegacyMod.MOD_ID)
public class PredelRiftManager {
 public static final int DURATION=80, COOLDOWN=240, RADIUS=3; public static final double RANGE=8.0, FALLBACK_DAMAGE=2.0;
 private static final Map<ResourceKey<Level>,Map<BlockPos,UUID>> OWNED=new HashMap<>(); private static final ResourceLocation IMMUNE=new ResourceLocation(KitchenLegacyMod.MOD_ID,"rift_immune");
 public static boolean use(ServerPlayer p){ if(!p.isAlive()||p.isSpectator())return false; ItemStack st=p.getMainHandItem(); if(!st.is(ModItems.PREDEL.get())||p.getCooldowns().isOnCooldown(ModItems.PREDEL.get()))return false; ServerLevel l=p.serverLevel(); Vec3 eye=p.getEyePosition(); Vec3 end=eye.add(p.getViewVector(1).scale(RANGE)); BlockHitResult hit=l.clip(new ClipContext(eye,end,ClipContext.Block.OUTLINE,ClipContext.Fluid.NONE,p)); if(hit.getType()!=HitResult.Type.BLOCK||!l.hasChunkAt(hit.getBlockPos()))return false; List<BlockPos> valid=new ArrayList<>(); for(BlockPos pos:plane(hit.getBlockPos(),hit.getDirection())) if(canPhase(p,l,pos)) valid.add(pos.immutable()); if(valid.isEmpty())return false; create(p,l,valid); p.getCooldowns().addCooldown(ModItems.PREDEL.get(),COOLDOWN); return true; }
 private static List<BlockPos> plane(BlockPos c, Direction f){ List<BlockPos> r=new ArrayList<>(9); for(int a=-1;a<=1;a++)for(int b=-1;b<=1;b++){ if(f.getAxis()==Direction.Axis.X)r.add(c.offset(0,b,a)); else if(f.getAxis()==Direction.Axis.Z)r.add(c.offset(a,b,0)); else r.add(c.offset(a,0,b)); } return r; }
 private static boolean canPhase(ServerPlayer p,ServerLevel l,BlockPos pos){ if(!l.hasChunkAt(pos)||isOwned(l.dimension(),pos))return false; BlockState s=l.getBlockState(pos); if(s.isAir()||s.getFluidState().isSource()||!s.getFluidState().isEmpty()||l.getBlockEntity(pos)!=null)return false; if(s.is(BlockTags.create(IMMUNE)))return false; Block b=s.getBlock(); if(b==Blocks.BEDROCK||b==Blocks.BARRIER||b instanceof BaseEntityBlock||b instanceof DoorBlock||b instanceof BedBlock||b instanceof DoublePlantBlock)return false; String id=net.minecraft.core.registries.BuiltInRegistries.BLOCK.getKey(b).getPath(); if(id.contains("portal")||id.contains("command")||id.contains("structure")||id.contains("jigsaw")||id.contains("piston_head")||id.contains("moving_piston"))return false; if(!p.mayUseItemAt(pos, Direction.UP, p.getMainHandItem()))return false; return !MinecraftForge.EVENT_BUS.post(new PredelRiftPermissionEvent(p,l,pos,s)); }
 private static void create(ServerPlayer p,ServerLevel l,List<BlockPos> positions){ UUID id=UUID.randomUUID(); List<RiftBlockSnapshot> snaps=new ArrayList<>(); for(BlockPos pos:positions){ snaps.add(new RiftBlockSnapshot(pos,l.getBlockState(pos))); own(l.dimension(),pos,id); l.setBlock(pos,ModBlocks.VOID_PHASE_BLOCK.get().defaultBlockState(),Block.UPDATE_CLIENTS|Block.UPDATE_KNOWN_SHAPE|Block.UPDATE_SUPPRESS_DROPS); particles(l,pos); } RiftInstance r=new RiftInstance(id,p.getUUID(),l.dimension(),snaps,l.getGameTime(),l.getGameTime()+DURATION); data(l).rifts.add(r); data(l).setDirty(); }
 @SubscribeEvent public static void tick(TickEvent.LevelTickEvent e){ if(e.phase!=TickEvent.Phase.END||e.level.isClientSide||!(e.level instanceof ServerLevel l))return; restoreDue(l); }
 @SubscribeEvent public static void chunk(ChunkEvent.Load e){ if(!e.getLevel().isClientSide()&&e.getLevel() instanceof ServerLevel l)restoreDue(l); }
 private static void restoreDue(ServerLevel l){ PredelRiftSavedData d=data(l); boolean dirty=false; Iterator<RiftInstance> it=d.rifts.iterator(); while(it.hasNext()){ RiftInstance r=it.next(); if(!r.dimension().equals(l.dimension())||l.getGameTime()<r.restoreGameTime())continue; List<RiftBlockSnapshot> remain=new ArrayList<>(); for(RiftBlockSnapshot s:r.blocks()){ if(!l.hasChunkAt(s.position())){remain.add(s);continue;} UUID currentOwner=owner(l.dimension(),s.position()); if(currentOwner!=null&&!Objects.equals(currentOwner,r.riftId()))continue; release(l.dimension(),s.position()); if(l.getBlockState(s.position()).is(ModBlocks.VOID_PHASE_BLOCK.get())){ evacuate(l,s.position()); l.setBlock(s.position(),s.originalState(),Block.UPDATE_CLIENTS|Block.UPDATE_KNOWN_SHAPE|Block.UPDATE_SUPPRESS_DROPS); particles(l,s.position()); } else KitchenLegacyMod.LOGGER.warn("Predel rift service block at {} was replaced; not overwriting",s.position()); dirty=true; } if(remain.isEmpty())it.remove(); else {it.remove(); d.rifts.add(new RiftInstance(r.riftId(),r.ownerPlayerId(),r.dimension(),remain,r.createdGameTime(),0)); break;} } if(dirty)d.setDirty(); }
 private static void evacuate(ServerLevel l,BlockPos pos){ AABB box=new AABB(pos); for(Entity e:l.getEntities((Entity)null,box,Entity::isAlive)){ Vec3 safe=findSafe(l,e,pos); e.teleportTo(safe.x,safe.y,safe.z); if(safe.y>pos.getY()+RADIUS){ e.hurt(l.damageSources().magic(),(float)FALLBACK_DAMAGE); Vec3 push=e.position().subtract(Vec3.atCenterOf(pos)).normalize().scale(.25); e.push(push.x,.15,push.z); } } }
 private static Vec3 findSafe(ServerLevel l,Entity e,BlockPos c){ for(int r=1;r<=RADIUS;r++)for(BlockPos p:BlockPos.betweenClosed(c.offset(-r,-r,-r),c.offset(r,r,r))) if(!p.equals(c)&&l.noCollision(e,e.getBoundingBox().move(Vec3.atBottomCenterOf(p).subtract(e.position())))&&l.getFluidState(p).isEmpty()&&!l.getBlockState(p).is(Blocks.FIRE))return Vec3.atBottomCenterOf(p); return Vec3.atBottomCenterOf(c.above(RADIUS+1)); }
 private static PredelRiftSavedData data(ServerLevel l){ return l.getDataStorage().computeIfAbsent(PredelRiftSavedData::load,PredelRiftSavedData::new,PredelRiftSavedData.NAME); }
 private static void particles(ServerLevel l,BlockPos p){ l.sendParticles(ModParticleTypes.VOID_RIFT.get(),p.getX()+.5,p.getY()+.5,p.getZ()+.5,12,.55,.55,.55,.02); }
 private static Map<BlockPos,UUID> map(ResourceKey<Level>d){return OWNED.computeIfAbsent(d,k->new HashMap<>());} private static boolean isOwned(ResourceKey<Level>d,BlockPos p){return map(d).containsKey(p);} private static UUID owner(ResourceKey<Level>d,BlockPos p){return map(d).get(p);} private static void own(ResourceKey<Level>d,BlockPos p,UUID id){map(d).put(p.immutable(),id);} private static void release(ResourceKey<Level>d,BlockPos p){map(d).remove(p);} }
